### ISSUE TITLE
Accordion Stopped working this morning

### ISSUE THREAD

**Issue by a-alher** [OlivierCC/spfx-40-fantastics#107]
Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
***Failed to load component "89d609dd-9fb6-4353-aab4-6215ac1bb7f6" (Accordion). Original error: ***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/jquery_510295b52d8a7cc774bf4fb013893d1e.js' for resource 'jquery' in component '89d609dd-9fb6-4353-aab4-6215ac1bb7f6' (Accordion). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

***INNERERROR:
***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/jquery_510295b52d8a7cc774bf4fb013893d1e.js' for resource 'jquery' in component '89d609dd-9fb6-4353-aab4-6215ac1bb7f6' (Accordion). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:4:53495)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:20:48986)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:20:112759)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:20:108790)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-09-13.009/sp-pages-assembly_en-us_ec9244e0470ebea1d6ad4db7f56d00c0.js:20:45200

**Comment by Colbz** [comment]
I'm showing the same error for all webparts. It looks like the site is completely down

**Comment by forrman** [comment]
We also seeing the same HTTPS cert error on our sites using these webparts.

**Comment by DWahry** [comment]
Yep, think it's down. Wish Microsoft would just release some official versions of these webparts!

**Comment by cconry1** [comment]
We are seeing the same error.

**Comment by csvang** [comment]
It seems to be working again.

**Comment by OlivierCC** [comment]
CDN was down, webparts are now available
