### ISSUE TITLE
Fixed Build & made full width

### ISSUE THREAD

**Issue by SharePointPro** [OlivierCC/spfx-40-fantastics#116]
If anyone is interested, or even better wants to help contribute, I've forked this project and made it so it builds and also made the Tile Menu work on Full Screen Mode:

You can find it here:

https://github.com/SharePointPro/spfx-40-fantastics-Sppro

**Comment by KDronadula** [comment]
Hi ,

I have build the the new code and deployed. My News carousel is giving errors

Any insights / help will be appreciated

SPLoaderError.loadComponentError]:
***Failed to load component "3f378f3d-733d-34b6-8470-17317bb0b275" (NewsCarousel). Original error: ***Failed to load URL 'https://cdn.jsdelivr.net/gh/SharePointPro/spfx40Js/spfx-40-fantastics-sppro-master-sp-client-custom-fields_strings_en-us_517cbd7b26367d7a6cbe94ede5a0f7b8.js' for resource 'sp-client-custom-fields/strings' in component '3f378f3d-733d-34b6-8470-17317bb0b275' (NewsCarousel). The file was not found in the server.

***INNERERROR:
***Failed to load URL 'https://cdn.jsdelivr.net/gh/SharePointPro/spfx40Js/spfx-40-fantastics-sppro-master-sp-client-custom-fields_strings_en-us_517cbd7b26367d7a6cbe94ede5a0f7b8.js' for resource 'sp-client-custom-fields/strings' in component '3f378f3d-733d-34b6-8470-17317bb0b275' (NewsCarousel). The file was not found in the server.
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_b42c2b13dd24a6e35fee4d5ad6a3d36c.js:4:53651)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_b42c2b13dd24a6e35fee4d5ad6a3d36c.js:20:118842)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_b42c2b13dd24a6e35fee4d5ad6a3d36c.js:20:128533)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_b42c2b13dd24a6e35fee4d5ad6a3d36c.js:20:124564)
    at https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_b42c2b13dd24a6e35fee4d5ad6a3d36c.js:20:115056

**Comment by SharePointPro** [comment]
it looks like you have taken the code from my forked repo..
The problem is every time a build is done it creates new javascript files that need to be hosted, I'll need to find a solution for that.
But in the meantime you can either use the pre-compiled package, or update the CDN urls to your own CDN and host the files found in the build after you compile.
You just need to search for the folder with the file "spfx-40-fantastics-sppro-master-sp-client-custom-fields_strings_en-us_517cbd7b26367d7a6cbe94ede5a0f7b8.js" and host it yourself.

**Comment by KDronadula** [comment]
Thank you ! that worked. Successfully updated to 1.1.0.0 version. 

We are facing an issue with News Carousel and News slider web-parts which ever have Manage data items. We don't see  "X" to close out in the pop up where we add/edit/delete items and it freezes and wont go back to main page.  

Any help is much appreciated.

**Comment by SharePointPro** [comment]
yes I also faced this problem.  SharePoint must have changed a bit since Oliver released this. if you look at my fork, I added a polyfill.css file to the tilemenu webpart. if you add this same polyfill css to the new carousel it will fix it. (perhaps write the comments on my forked project (https://github.com/SharePointPro/spfx-40-fantastics-Sppro/) as its more relevant there)

**Comment by Eakawie** [comment]
In another thread a developer fixed a bunch of CDN issues that were causing problems with the FCK editor.  He hasn't done a proper fork, as far as I can see and is just making his version available through Dropbox. Any chance you could merge your changes with his? https://github.com/OlivierCC/spfx-40-fantastics/issues/29#issuecomment-577612585
