### ISSUE TITLE
spfx-40-fantastics error

### ISSUE THREAD

**Issue by ntaflosa** [OlivierCC/spfx-40-fantastics#131]
[SPLoaderError.loadComponentError]:
Failed to load component "60564c9b-8561-489d-9ff7-1846c8358964" (NewsTicker). Original error: Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/spfx-40-fantastics-sp-client-custom-fields_strings_de-de_8a7a0542e5fb3e4214126f097f3c62aa.js' for resource 'sp-client-custom-fields/strings' in component '60564c9b-8561-489d-9ff7-1846c8358964' (NewsTicker). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

INNERERROR:
Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/spfx-40-fantastics-sp-client-custom-fields_strings_de-de_8a7a0542e5fb3e4214126f097f3c62aa.js' for resource 'sp-client-custom-fields/strings' in component '60564c9b-8561-489d-9ff7-1846c8358964' (NewsTicker). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
CALLSTACK:
Error
    at t [as constructor] (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_2af4b80f4c59eced0378e201f27628d3.js:65:19844)
    at new t (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_2af4b80f4c59eced0378e201f27628d3.js:65:163119)
    at Function.e.buildErrorWithVerboseLog (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_2af4b80f4c59eced0378e201f27628d3.js:65:200558)
    at Function.e.buildLoadComponentError (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_de-de_2af4b80f4c59eced0378e201f27628d3.js:65:196603)
    at https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_de-de_dbaf73e391f98dcbc776.js:1:11895

**Comment by Nathure** [comment]
Hello, 
I have the same error for animated text web part. :-(

TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
Failed to load component "a4aacd2d-2a55-475c-5483-51a37437b388" (AnimatedText). Original error: Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/spfx-40-fantastics-animatedtextstrings_en-us_58a06e1f431b113fb134f0985c13fd17.js' for resource 'AnimatedTextStrings' in component 'a4aacd2d-2a55-475c-5483-51a37437b388' (AnimatedText). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

INNERERROR:
Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/spfx-40-fantastics-animatedtextstrings_en-us_58a06e1f431b113fb134f0985c13fd17.js' for resource 'AnimatedTextStrings' in component 'a4aacd2d-2a55-475c-5483-51a37437b388' (AnimatedText). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
CALLSTACK:
Error
    at t [as constructor] (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_c5b741fefc9b5a5c92ad9f6b2face310.js:65:19844)
    at new t (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_c5b741fefc9b5a5c92ad9f6b2face310.js:65:162825)
    at Function.e.buildErrorWithVerboseLog (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_c5b741fefc9b5a5c92ad9f6b2face310.js:65:200144)
    at Function.e.buildLoadComponentError (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_c5b741fefc9b5a5c92ad9f6b2face310.js:65:196189)
    at https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_dbaf73e391f98dcbc776.js:1:11895

**Comment by Nathure** [comment]
@OlivierCC do you have a solution or an idea ?

**Comment by ManuSquall** [comment]
Hello, same error here too, does anybody have a solution 👀👀👀?


[SPLoaderError.loadComponentError]:
Failed to load component "60564c9b-8561-489d-9ff7-1846c8358964" (NewsTicker). Original error: Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/spfx-40-fantastics-sp-client-custom-fields_strings_fr-fr_8d78975f5035cf5fe20ce99cca04a3a4.js' for resource 'sp-client-custom-fields/strings' in component '60564c9b-8561-489d-9ff7-1846c8358964' (NewsTicker). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

INNERERROR:
Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/spfx-40-fantastics-sp-client-custom-fields_strings_fr-fr_8d78975f5035cf5fe20ce99cca04a3a4.js' for resource 'sp-client-custom-fields/strings' in component '60564c9b-8561-489d-9ff7-1846c8358964' (NewsTicker). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
CALLSTACK:
Error
    at t [as constructor] (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_fr-fr_410a4939584cad32c6080befd8f58792.js:65:19844)
    at new t (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_fr-fr_410a4939584cad32c6080befd8f58792.js:65:163283)
    at Function.e.buildErrorWithVerboseLog (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_fr-fr_410a4939584cad32c6080befd8f58792.js:65:200660)
    at Function.e.buildLoadComponentError (https://modern.akamai.odsp.cdn.office.net/files/sp-client/sp-pages-assembly_fr-fr_410a4939584cad32c6080befd8f58792.js:65:196705)
    at https://modern.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_fr-fr_dbaf73e391f98dcbc776.js:1:11895
