### ISSUE TITLE
All webparts are broken as of today

### ISSUE THREAD

**Issue by baskb** [OlivierCC/spfx-40-fantastics#20]
When adding a spfx-40 webpart to a page, I receive the following error. I am using version 1.0.2.0.

**Something went wrong**
If the problem persists, contact the site administrator and give them the information in Technical Details.

Technical Details

***ERROR MESSAGE:
***Failed to load component "b6330715-c92a-479c-ae83-510474079988" (3DCarousel).
Original error: ***Failed to load entry point from component "b6330715-c92a-479c-ae83-510474079988" (3DCarousel).
Original error: Error loading https://component-id.invalid/b6330715-c92a-479c-ae83-510474079988_1.0
	Module exports cannot be changed externally.

***CALLSTACK:
Error: ***Failed to load component "b6330715-c92a-479c-ae83-510474079988" (3DCarousel).
Original error: ***Failed to load entry point from component "b6330715-c92a-479c-ae83-510474079988" (3DCarousel).
Original error: Error loading https://component-id.invalid/b6330715-c92a-479c-ae83-510474079988_1.0
	Module exports cannot be changed externally.
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod-vstsfeed_2017-04-21.010/sp-loader_en-us_8c7001f8a00f4c91caa5559128b9a94f.js:88:47594)
   at k (https://spoprod-a.akamaihd.net/files/sp-client-prod-vstsfeed_2017-04-21.010/sp-loader_en-us_8c7001f8a00f4c91caa5559128b9a94f.js:88:2381)
   at L (https://spoprod-a.akamaihd.net/files/sp-client-prod-vstsfeed_2017-04-21.010/sp-loader_en-us_8c7001f8a00f4c91caa5559128b9a94f.js:88:2469)
   at I (https://spoprod-a.akamaihd.net/files/sp-client-prod-vstsfeed_2017-04-21.010/sp-loader_en-us_8c7001f8a00f4c91caa5559128b9a94f.js:88:2291)
   at D (https://spoprod-a.akamaihd.net/files/sp-client-prod-vstsfeed_2017-04-21.010/sp-loader_en-us_8c7001f8a00f4c91caa5559128b9a94f.js:88:1887)
   at m (https://spoprod-a.akamaihd.net/files/sp-client-prod-vstsfeed_2017-04-21.010/sp-loader_en-us_8c7001f8a00f4c91caa5559128b9a94f.js:88:570)

**Comment by semisweet** [comment]
I noticed this a few weeks ago for News Carousel:

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
***ERROR MESSAGE:
***Failed to load component "3f378f3d-733d-34b6-8470-17317bb0b275" (NewsCarousel).
Original error: ***Failed to load entry point from component "3f378f3d-733d-34b6-8470-17317bb0b275" (NewsCarousel).
Original error: Error loading https://component-id.invalid/3f378f3d-733d-34b6-8470-17317bb0b275_1.0
	Module exports cannot be changed externally.

***CALLSTACK:
Error: ***Failed to load component "3f378f3d-733d-34b6-8470-17317bb0b275" (NewsCarousel).
Original error: ***Failed to load entry point from component "3f378f3d-733d-34b6-8470-17317bb0b275" (NewsCarousel).
Original error: Error loading https://component-id.invalid/3f378f3d-733d-34b6-8470-17317bb0b275_1.0
	Module exports cannot be changed externally.
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-04-28.005/classic-pages-assembly_en-us_32ab23bd087be6bbc4a672b4e49e6a9f.js:109:50238

**Comment by warwickbuilds** [comment]
Looks like this issues or one related is back today
