### ISSUE TITLE
downloaded the webpart and added into app catolog. getting error while adding webpart on modern pages

### ISSUE THREAD

**Issue by raghu522** [OlivierCC/spfx-40-fantastics#35]
Something went wrong

If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
***Failed to load component "b6330715-c92a-479c-ae83-510474079988" (3DCarousel).
Original error: ***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/jquery_510295b52d8a7cc774bf4fb013893d1e.js' for resource 'jquery' in component 'b6330715-c92a-479c-ae83-510474079988' (3DCarousel). There was a network problem.
This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

***INNERERROR:
***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/jquery_510295b52d8a7cc774bf4fb013893d1e.js' for resource 'jquery' in component 'b6330715-c92a-479c-ae83-510474079988' (3DCarousel). There was a network problem.
This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.011/sp-pages-assembly_en-us_b91a3c7aa8341a6dbe6d1f073874c5c4.js:351:10483)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.011/sp-pages-assembly_en-us_b91a3c7aa8341a6dbe6d1f073874c5c4.js:905:16704)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.011/sp-pages-assembly_en-us_b91a3c7aa8341a6dbe6d1f073874c5c4.js:905:13917)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.011/sp-pages-assembly_en-us_b91a3c7aa8341a6dbe6d1f073874c5c4.js:905:11726)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.011/sp-pages-assembly_en-us_b91a3c7aa8341a6dbe6d1f073874c5c4.js:905:110506
    at <anonymous>

. Press Enter to navigate inside the web part. When inside, use Alt+F10 to go to toolbar, use Alt+P to move focus to the property pane and use Escape to exit the web part.

**Comment by screwfacekilla** [comment]
How can we help ensure "somethings don't go wrong" ?
..!.. (o_O) ..Y
[]D[][]\/[][]D

On Jul 29, 2017, at 10:02 PM, raghu522 <notifications@github.com<mailto:notifications@github.com>> wrote:


Something went wrong

If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
***Failed to load component "b6330715-c92a-479c-ae83-510474079988" (3DCarousel).
Original error: ***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/jquery_510295b52d8a7cc774bf4fb013893d1e.js' for resource 'jquery' in component 'b6330715-c92a-479c-ae83-510474079988' (3DCarousel). There was a network problem.
This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

***INNERERROR:
***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/jquery_510295b52d8a7cc774bf4fb013893d1e.js' for resource 'jquery' in component 'b6330715-c92a-479c-ae83-510474079988' (3DCarousel). There was a network problem.
This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
***CALLSTACK:
Error
at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.011/sp-pages-assembly_en-us_b91a3c7aa8341a6dbe6d1f073874c5c4.js:351:10483)
at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.011/sp-pages-assembly_en-us_b91a3c7aa8341a6dbe6d1f073874c5c4.js:905:16704)
at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.011/sp-pages-assembly_en-us_b91a3c7aa8341a6dbe6d1f073874c5c4.js:905:13917)
at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.011/sp-pages-assembly_en-us_b91a3c7aa8341a6dbe6d1f073874c5c4.js:905:11726)
at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.011/sp-pages-assembly_en-us_b91a3c7aa8341a6dbe6d1f073874c5c4.js:905:110506
at

. Press Enter to navigate inside the web part. When inside, use Alt+F10 to go to toolbar, use Alt+P to move focus to the property pane and use Escape to exit the web part.

**Comment by Ragnarok99** [comment]
same problem here !!! \0/

**Comment by warwickbuilds** [comment]
Seems very unreliable the hosting of these resources... hopefully Oliver respond with options, as they are very useful

**Comment by screwfacekilla** [comment]
Yeah I'd assume his expectation was that we bring the JavaScript resources into our own host and build the package again. That's what we are planning to do. Olivier is really good about responding and providing recommendations

On Aug 6, 2017, at 12:38 AM, Warwick Ward <notifications@github.com<mailto:notifications@github.com>> wrote:


Seems very unreliable the hosting of these resources... hopefully Oliver respond with options, as they are very useful

**Comment by warwickbuilds** [comment]
Is it a conflict with something loading in the SharePoint modern pages do you think?

As running the solution in local workbench they run fine

**Comment by warwickbuilds** [comment]
even after hosting all the deploy files locally, I can't now get past this error. Anyone have any ideas

[SPLoaderError.loadComponentError]:
***Failed to load component "89d609dd-9fb6-4353-aab4-6215ac1bb7f6" (Accordion).
Original error: ***Failed to load path dependency "jqueryui" from component "89d609dd-9fb6-4353-aab4-6215ac1bb7f6" (Accordion).
Original error: Cannot read property 'ui' of undefined

***INNERERROR:
***Failed to load path dependency "jqueryui" from component "89d609dd-9fb6-4353-aab4-6215ac1bb7f6" (Accordion).
Original error: Cannot read property 'ui' of undefined
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-21.015/sp-classic-page-assembly_en-us_99df35401a95853a1847e55b244b6917.js:206:10483)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-21.015/sp-classic-page-assembly_en-us_99df35401a95853a1847e55b244b6917.js:501:19050)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-21.015/sp-classic-page-assembly_en-us_99df35401a95853a1847e55b244b6917.js:501:12597)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-21.015/sp-classic-page-assembly_en-us_99df35401a95853a1847e55b244b6917.js:501:8666)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-21.015/sp-classic-page-assembly_en-us_99df35401a95853a1847e55b244b6917.js:501:107462
    at <anonymous>

**Comment by FaganSC** [comment]
I had this problem as well, and then just yesterday it stopped. I figure it was a bad deployment on the O365 side.

**Comment by OlivierCC** [comment]
If you are using the precompiled web part package, this sample kit is hosted on a very basic CDN on Azure. This CDN is very basic without high availibity options. I upgraded the hosting model some days ago, but it is still a basic subscriptions.

If the behavior is enough for you, you can still use this CDN. If you want to have a better experience, I advise you really to use your own CDN to host the Javascript ressources as suggested by @screwfacekilla.

**Comment by warwickbuilds** [comment]
I actually tried that, hosting everything in the deploy folder and changing the CDN path, but still got issues, which is why I figured it was conflicts happening or changes Microsoft was making. Though maybe I didn't configure something right in the config, still learning the finer aspects of SPFx.

**Comment by anmolsinghchauhan** [comment]
@OlivierCC  i tried hosting web part in our own CDN. But still getting same error. Can you give any tips on how to resolve it.

**Comment by ChingisR** [comment]
Hello

How to download the contents of the spfx40fantastics.azureedge.net/spfx40fantastics to local SP library?
