### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by bubhat** [OlivierCC/spfx-40-fantastics#36]
We added these webparts to our SP online sites, worked great. Suddenly stopped working. 
Discovered that the following error is due to me being the first release customer. Will this be fixed please?
Error:
[SPLoaderError.loadComponentError]:

***Failed to load component "3f3e8f3d-033d-34b6-8450-173122222275" (SimpleCarousel).

Original error: ***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/unitegallery_7d9eb985d2d3c164e19835ea4e33161e.js' for resource 'unitegallery' in component '3f3e8f3d-033d-34b6-8450-173122222275' (SimpleCarousel). There was a network problem.

This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

***INNERERROR:

***Failed to load URL 'https://spfx40fantastics.azureedge.net/spfx40fantastics/unitegallery_7d9eb985d2d3c164e19835ea4e33161e.js' for resource 'unitegallery' in component '3f3e8f3d-033d-34b6-8450-173122222275' (SimpleCarousel). There was a network problem.

This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

***CALLSTACK:

Error
   at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.013/sp-pages-assembly_en-us_12ebeae6ae845ba9a2f4bd9de962fb90.js:351:10315)
   at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.013/sp-pages-assembly_en-us_12ebeae6ae845ba9a2f4bd9de962fb90.js:905:16696)
   at e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.013/sp-pages-assembly_en-us_12ebeae6ae845ba9a2f4bd9de962fb90.js:905:13911)
   at e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.013/sp-pages-assembly_en-us_12ebeae6ae845ba9a2f4bd9de962fb90.js:905:11714)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-07-14.013/sp-pages-assembly_en-us_12ebeae6ae845ba9a2f4bd9de962fb90.js:905:104715)

**Comment by Ragnarok99** [comment]
I've the same problem, any solution to this?

**Comment by screwfacekilla** [comment]
We had this issue, and then it just resolved itself.

There’s something with the SSL Cert
